apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-services-ordering
  labels:
    version: dev
    product: globoticket-services-ordering
spec:
  selector:
    app: globoticket-services-ordering
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-services-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globoticket-services-ordering
  template:
    metadata:
      labels:
        app: globoticket-services-ordering
    spec:
      containers:
      - name: globoticket-services-ordering
        image: jbdgloboticketacr.azurecr.io/globoticket.services.ordering:1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__DefaultConnection
          valueFrom: 
            secretKeyRef:
              name: ordering-db
              key: connectionstring
        - name: ServiceBusConnectionString
          value: Endpoint=sb://globoticket.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Hi0hqUzgNIhGOcceT/gW4B23fHSlbVM+FPAxjq3zZTc=
        - name: CheckoutMessageTopic
          value: checkoutmessage
        - name: OrderPaymentRequestMessageTopic
          value: orderpaymentrequestmessage
        - name: OrderPaymentUpdatedMessageTopic
          value: orderpaymentupdatedmessage
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.15"
      imagePullSecrets:
        - name: acr-secret