apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-services-shoppingbasket
  labels:
    version: prod
    product: globoticket-services-shoppingbasket
spec:
  selector:
    app: globoticket-services-shoppingbasket
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-services-shoppingbasket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globoticket-services-shoppingbasket
  template:
    metadata:
      labels:
        app: globoticket-services-shoppingbasket
    spec:
      containers:
      - name: globoticket-services-shoppingbasket
        image: globoticketacr.azurecr.io/globoticket.services.shoppingbasket:1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__DefaultConnection
          valueFrom: 
            secretKeyRef:
              name: shoppingbasket-db
              key: connectionstring
        - name: ApiConfigs__EventCatalog__Uri
          value: http://svc-globoticket-services-eventcatalog
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: acr-secret
